from __future__ import annotations

class NOC:
  REGS_START_ADDR = 0xFFB20000
  STATUS_BASE = 0xFFB20200
  CMD_BUF_OFFSET_BIT = 11
  INSTANCE_OFFSET_BIT = 16
  CFG_BASE = REGS_START_ADDR + 0x100

  TARG_ADDR_LO = REGS_START_ADDR + 0x00
  TARG_ADDR_MID = REGS_START_ADDR + 0x04
  TARG_ADDR_COORDINATE = REGS_START_ADDR + 0x08
  RET_ADDR_LO = REGS_START_ADDR + 0x0C
  RET_ADDR_MID = REGS_START_ADDR + 0x10
  RET_ADDR_COORDINATE = REGS_START_ADDR + 0x14
  CTRL = REGS_START_ADDR + 0x1C
  AT_LEN_BE = REGS_START_ADDR + 0x20
  AT_LEN_BE_1 = REGS_START_ADDR + 0x24
  AT_DATA = REGS_START_ADDR + 0x28
  CMD_CTRL = REGS_START_ADDR + 0x40

  CTRL_SEND_REQ = 1
  PCIE_MID = 0x10000000
  COORD_MASK = 0xFFFFFF

  CMD_CPY = 0
  CMD_AT = 1
  CMD_WR = 1 << 1
  CMD_WR_INLINE = 1 << 3
  CMD_RESP_MARKED = 1 << 4
  CMD_BRCST_PACKET = 1 << 5
  CMD_VC_LINKED = 1 << 6
  CMD_VC_STATIC = 1 << 7
  CMD_PATH_RESERVE = 1 << 8
  CMD_STATIC_VC_1 = 1 << 13
  CMD_STATIC_VC_5 = 5 << 13

  CMD_RD_FIELD = CMD_CPY | CMD_RESP_MARKED | CMD_VC_STATIC | CMD_STATIC_VC_1
  CMD_WR_FIELD = CMD_CPY | CMD_WR | CMD_RESP_MARKED | CMD_VC_STATIC | CMD_STATIC_VC_1
  CMD_WR_POSTED_FIELD = CMD_CPY | CMD_WR | CMD_VC_STATIC | CMD_STATIC_VC_1
  CMD_WR_MCAST_UNLINK_FIELD = (
    CMD_CPY | CMD_WR | CMD_RESP_MARKED | CMD_VC_STATIC |
    CMD_STATIC_VC_5 | CMD_BRCST_PACKET | CMD_PATH_RESERVE
  )
  CMD_WR_MCAST_LINKED_FIELD = CMD_WR_MCAST_UNLINK_FIELD | CMD_VC_LINKED
  CMD_INLINE_FIELD = CMD_WR_FIELD | CMD_WR_INLINE
  CMD_AT_INC_FIELD = CMD_AT | CMD_RESP_MARKED | CMD_VC_STATIC | CMD_STATIC_VC_1

  AT_INS_INCR_GET = 0x1
  AT_INS_SHIFT = 12
  AT_WRAP_SHIFT = 2
  AT_INCR_GET = (AT_INS_INCR_GET << AT_INS_SHIFT) | (31 << AT_WRAP_SHIFT)

  MAX_BURST_SIZE = 16 * 1024

  NIU_MST_ATOMIC_RESP_RECEIVED = 0x00
  NIU_MST_WR_ACK_RECEIVED = 0x04
  NIU_MST_RD_RESP_RECEIVED = 0x08
  NIU_MST_NONPOSTED_WR_REQ_SENT = 0x28
