from enum import IntEnum
from struct import Struct

Rect = tuple[tuple[int, int], tuple[int, int]]

ALIGN = 64; MAX_WRITE_SIZE = 16 * 1024; MAX_RECORD_SIZE = 64 * 1024; PAGE_SIZE = 4096

CQ_STATE = 0x1000
PREFETCH_DOORBELL = CQ_STATE
PREFETCH_PCIE_BASE = CQ_STATE + 0x08
PREFETCH_READ_PTR = CQ_STATE + 0x0C
PREFETCH_DISPATCH_READ = CQ_STATE + 0x10
PREFETCH_TRACE_ACTIVE = CQ_STATE + 0x14
PREFETCH_TRACE_CURSOR = CQ_STATE + 0x18
PREFETCH_TRACE_END = CQ_STATE + 0x1C
PREFETCH_RECORD_SIZE = CQ_STATE + 0x20
PREFETCH_READ_PUBLISH = CQ_STATE + 0x30  # Scalar NoC sources are 16-byte aligned.
# The largest CQ record is 64 KiB. Keep staging clear of the BRISC firmware
# image and the small CQ state area below 0x2000.
PREFETCH_STAGING = 0x20000
DISPATCH_PUBLISHED = CQ_STATE
DISPATCH_RING_BASE = 0x20000; DISPATCH_RING_PAGES = 320
DISPATCH_RING_END = DISPATCH_RING_BASE + DISPATCH_RING_PAGES * PAGE_SIZE
DISPATCH_SCRATCH = DISPATCH_RING_END
DISPATCH_GO = DISPATCH_SCRATCH + 0x40
DISPATCH_DONE_COUNT = DISPATCH_SCRATCH + 0x50
DISPATCH_READ_PUBLISH = DISPATCH_SCRATCH + 0x60
DISPATCH_SIGNAL = DISPATCH_SCRATCH + 0x70
DISPATCH_DRAM_PUT = DISPATCH_SCRATCH + 0x80
DISPATCH_DRAM_READ = DISPATCH_SCRATCH + 0x90  # NoC read destination must be 16-byte aligned.
DRAM_PUBLISHED = CQ_STATE
DRAM_NCRISC_READ = CQ_STATE + 4
DRAM_BRISC_READY = CQ_STATE + 8
DRAM_NCRISC_READY = CQ_STATE + 0xC
DRAM_READ_PUBLISH = CQ_STATE + 0x60
DRAM_QUEUE_BASE = 0x2000
DRAM_QUEUE_ENTRIES = 32
DRAM_BRISC_STAGING = 0x20000
DRAM_NCRISC_STAGING = 0x30000
HOST_ISSUE_SIZE = 4 << 20
HOST_COMPLETION_SIZE = PAGE_SIZE
HOST_TRACE_SIZE = 256 << 20
HOST_LIVE_SIZE = 128 << 10

class Op(IntEnum):
  PAD = 0
  UNICAST_WRITE = 1
  MCAST_WRITE = 2
  RUN = 3
  DRAM_RECORD = 4
  SIGNAL = 5
  TRACE = 6
  DRAM_COPY = 7
  WAIT = 8
  TIMESTAMP = 9
  DMA = 10

class PacketLayout:
  HEADER = Struct("<BxHIII")
  UNICAST_TARGET = Struct("<I")
  MCAST_TARGET = Struct("<II")

  OP = 0
  TARGET_COUNT = 2
  TOTAL_SIZE = 4
  ADDRESS = 8
  DATA_SIZE = 12
  DRAM_COORD = HEADER.size
  SIGNAL_TARGET_LO = ADDRESS
  SIGNAL_TARGET_MID = DATA_SIZE
  SIGNAL_VALUE = HEADER.size
  TRACE_SOURCE_LO = ADDRESS
  TRACE_SOURCE_MID = DATA_SIZE
  TRACE_SIZE = HEADER.size
  COPY_SOURCE_LO = HEADER.size
  COPY_SOURCE_MID = COPY_SOURCE_LO + 4
  COPY_TILE_COUNT = COPY_SOURCE_MID + 4
  COPY_BANKS = COPY_TILE_COUNT + 4
  COPY_DIRECTION = COPY_BANKS + 4
  WRITE_TARGETS = HEADER.size
  RUN_TEMPLATE = HEADER.size
  RUN_TARGETS = HEADER.size + 8


BOOT_PCIE_MID = CQ_STATE + 0x80
BOOT_BANKS = CQ_STATE + 0x84
BOOT_COORDS = CQ_STATE + 0xA0
DMA_PAGE_SIZE = 2048
