// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

// blackhole-py CQ topology — core coordinates and grid parameters are overridable
// via -D flags from the compiler to support different board types (p100a, p150a, etc).
// Defaults match p100a: prefetch (14,2), dispatch (14,3), 118 worker cores.

#ifndef DISPATCH_KERNEL
#define DISPATCH_KERNEL 1
#endif

#ifndef FD_CORE_TYPE
#define FD_CORE_TYPE 0
#endif

#ifndef IS_H_VARIANT
#define IS_H_VARIANT 1
#endif

#ifndef IS_D_VARIANT
#define IS_D_VARIANT 1
#endif

// --- overridable core coordinates (set via -D*_OVERRIDE flags) ---
#ifdef MY_NOC_X_OVERRIDE
#define CQ_PREFETCH_X MY_NOC_X_OVERRIDE
#define CQ_DISPATCH_X MY_NOC_X_OVERRIDE
#else
#define CQ_PREFETCH_X 14
#define CQ_DISPATCH_X 14
#endif

#ifdef MY_NOC_Y_OVERRIDE
#define CQ_PREFETCH_Y MY_NOC_Y_OVERRIDE
#define CQ_DISPATCH_Y (MY_NOC_Y_OVERRIDE + 1)
#else
#define CQ_PREFETCH_Y 2
#define CQ_DISPATCH_Y 3
#endif

#ifdef UPSTREAM_NOC_X_OVERRIDE
#define CQ_UPSTREAM_X UPSTREAM_NOC_X_OVERRIDE
#else
#define CQ_UPSTREAM_X 14
#endif

#ifdef UPSTREAM_NOC_Y_OVERRIDE
#define CQ_UPSTREAM_Y UPSTREAM_NOC_Y_OVERRIDE
#else
#define CQ_UPSTREAM_Y 2
#endif

#ifdef DOWNSTREAM_NOC_X_OVERRIDE
#define CQ_DOWNSTREAM_X DOWNSTREAM_NOC_X_OVERRIDE
#else
#define CQ_DOWNSTREAM_X 14
#endif

#ifdef DOWNSTREAM_NOC_Y_OVERRIDE
#define CQ_DOWNSTREAM_Y DOWNSTREAM_NOC_Y_OVERRIDE
#else
#define CQ_DOWNSTREAM_Y 3
#endif

#ifdef DOWNSTREAM_SUBORDINATE_NOC_X_OVERRIDE
#define CQ_DOWNSTREAM_SUB_X DOWNSTREAM_SUBORDINATE_NOC_X_OVERRIDE
#else
#define CQ_DOWNSTREAM_SUB_X 14
#endif

#ifdef DOWNSTREAM_SUBORDINATE_NOC_Y_OVERRIDE
#define CQ_DOWNSTREAM_SUB_Y DOWNSTREAM_SUBORDINATE_NOC_Y_OVERRIDE
#else
#define CQ_DOWNSTREAM_SUB_Y 3
#endif

#ifdef WORKER_MCAST_GRID_OVERRIDE
#define CQ_WORKER_MCAST_GRID WORKER_MCAST_GRID_OVERRIDE
#else
#define CQ_WORKER_MCAST_GRID 0x8102CE
#endif

#ifdef NUM_WORKER_CORES_TO_MCAST_OVERRIDE
#define CQ_NUM_WORKER_CORES NUM_WORKER_CORES_TO_MCAST_OVERRIDE
#else
#define CQ_NUM_WORKER_CORES 118
#endif

#ifdef PACKED_WRITE_MAX_UNICAST_SUB_CMDS_OVERRIDE
#define CQ_PACKED_WRITE_MAX PACKED_WRITE_MAX_UNICAST_SUB_CMDS_OVERRIDE
#else
#define CQ_PACKED_WRITE_MAX 118
#endif

#if defined(COMPILE_FOR_BRISC) && (NOC_INDEX == 0)
// cq_prefetch.cpp
#define MY_NOC_X CQ_PREFETCH_X
#define MY_NOC_Y CQ_PREFETCH_Y
#define UPSTREAM_NOC_X CQ_UPSTREAM_X
#define UPSTREAM_NOC_Y CQ_UPSTREAM_Y
#define DOWNSTREAM_NOC_X CQ_DOWNSTREAM_X
#define DOWNSTREAM_NOC_Y CQ_DOWNSTREAM_Y
#define DOWNSTREAM_SUBORDINATE_NOC_X CQ_DOWNSTREAM_SUB_X
#define DOWNSTREAM_SUBORDINATE_NOC_Y CQ_DOWNSTREAM_SUB_Y
#define UPSTREAM_NOC_INDEX 0

#define DOWNSTREAM_CB_BASE 0x1A000
#define DOWNSTREAM_CB_LOG_PAGE_SIZE 12
#define DOWNSTREAM_CB_PAGES 128
#define MY_DOWNSTREAM_CB_SEM_ID 0
#define DOWNSTREAM_CB_SEM_ID 0

#define PCIE_BASE 0x40000100
#define PCIE_SIZE (64 * 1024 * 1024)
#define PREFETCH_Q_BASE 0x19840
#define PREFETCH_Q_SIZE 0xBFC
#define PREFETCH_Q_RD_PTR_ADDR 0x196C0
#define PREFETCH_Q_PCIE_RD_PTR_ADDR 0x196C4

#define CMDDAT_Q_BASE 0x1A440
#define CMDDAT_Q_SIZE (256 * 1024)
#define SCRATCH_DB_BASE 0x5A440
#define SCRATCH_DB_SIZE (128 * 1024)
#define DOWNSTREAM_SYNC_SEM_ID 2
#define CMDDAT_Q_PAGES 64
#define MY_UPSTREAM_CB_SEM_ID 3
#define UPSTREAM_CB_SEM_ID 3
#define CMDDAT_Q_LOG_PAGE_SIZE 12
#define CMDDAT_Q_BLOCKS 4

#define DISPATCH_S_BUFFER_BASE 0x9A000
#define MY_DISPATCH_S_CB_SEM_ID 1
#define DOWNSTREAM_DISPATCH_S_CB_SEM_ID 0
#define DISPATCH_S_BUFFER_SIZE (32 * 1024)
#define DISPATCH_S_CB_LOG_PAGE_SIZE 8
#define RINGBUFFER_SIZE 0

#elif defined(COMPILE_FOR_BRISC) && (NOC_INDEX == 1)
// cq_dispatch.cpp
#define MY_NOC_X CQ_DISPATCH_X
#define MY_NOC_Y CQ_DISPATCH_Y
#define UPSTREAM_NOC_X CQ_UPSTREAM_X
#define UPSTREAM_NOC_Y CQ_UPSTREAM_Y
#define DOWNSTREAM_NOC_X CQ_DOWNSTREAM_X
#define DOWNSTREAM_NOC_Y CQ_DOWNSTREAM_Y
#define DOWNSTREAM_SUBORDINATE_NOC_X CQ_DOWNSTREAM_SUB_X
#define DOWNSTREAM_SUBORDINATE_NOC_Y CQ_DOWNSTREAM_SUB_Y
#define UPSTREAM_NOC_INDEX 0

#define DISPATCH_CB_BASE 0x1A000
#define DISPATCH_CB_LOG_PAGE_SIZE 12
#define DISPATCH_CB_PAGES 128
#define DISPATCH_CB_BLOCKS 4
#define MY_DISPATCH_CB_SEM_ID 0
#define UPSTREAM_DISPATCH_CB_SEM_ID 0
#define UPSTREAM_SYNC_SEM 2

#define COMMAND_QUEUE_BASE_ADDR 0x40000000
#define COMPLETION_QUEUE_BASE_ADDR 0x44000100
#define COMPLETION_QUEUE_SIZE (32 * 1024 * 1024)
#define HOST_COMPLETION_Q_WR_PTR 128
#define DEV_COMPLETION_Q_WR_PTR 0x196D0
#define DEV_COMPLETION_Q_RD_PTR 0x196E0

#define DOWNSTREAM_CB_BASE 0
#define DOWNSTREAM_CB_SIZE 0
#define MY_DOWNSTREAM_CB_SEM_ID 1
#define DOWNSTREAM_CB_SEM_ID 1

#define SPLIT_DISPATCH_PAGE_PREAMBLE_SIZE 0
#define SPLIT_PREFETCH 0
#define PREFETCH_H_NOC_XY 0
#define PREFETCH_H_LOCAL_DOWNSTREAM_SEM_ADDR 0
#define PREFETCH_H_MAX_CREDITS 0

#define PACKED_WRITE_MAX_UNICAST_SUB_CMDS CQ_PACKED_WRITE_MAX
#define DISPATCH_S_SYNC_SEM_BASE_ADDR 0x19710
#define MAX_NUM_WORKER_SEMS 8
#define MAX_NUM_GO_SIGNAL_NOC_DATA_ENTRIES 256
#define MCAST_GO_SIGNAL_ADDR 0x370
#define UNICAST_GO_SIGNAL_ADDR 0x370
#define DISTRIBUTED_DISPATCHER 0
#define FIRST_STREAM_USED 48
#define VIRTUALIZE_UNICAST_CORES 0
#define NUM_VIRTUAL_UNICAST_CORES 0
#define NUM_PHYSICAL_UNICAST_CORES 0
#define WORKER_MCAST_GRID CQ_WORKER_MCAST_GRID
#define NUM_WORKER_CORES_TO_MCAST CQ_NUM_WORKER_CORES

#elif defined(COMPILE_FOR_NCRISC) && (NOC_INDEX == 1)
// cq_dispatch_subordinate.cpp
#define MY_NOC_X CQ_DISPATCH_X
#define MY_NOC_Y CQ_DISPATCH_Y
#define UPSTREAM_NOC_X CQ_UPSTREAM_X
#define UPSTREAM_NOC_Y CQ_UPSTREAM_Y
#define DOWNSTREAM_NOC_X CQ_DOWNSTREAM_X
#define DOWNSTREAM_NOC_Y CQ_DOWNSTREAM_Y

#define CB_BASE 0x9A000
#define CB_LOG_PAGE_SIZE 8
#define CB_SIZE (32 * 1024)
#define MY_DISPATCH_CB_SEM_ID 0
#define UPSTREAM_DISPATCH_CB_SEM_ID 1

#define DISPATCH_S_SYNC_SEM_BASE_ADDR 0x19710
#define MCAST_GO_SIGNAL_ADDR 0x370
#define UNICAST_GO_SIGNAL_ADDR 0x370
#define DISTRIBUTED_DISPATCHER 0
#define FIRST_STREAM_USED 48
#define MAX_NUM_WORKER_SEMS 8
#define MAX_NUM_GO_SIGNAL_NOC_DATA_ENTRIES 256
#define VIRTUALIZE_UNICAST_CORES 0
#define NUM_VIRTUAL_UNICAST_CORES 0
#define NUM_PHYSICAL_UNICAST_CORES 0
#define WORKER_MCAST_GRID CQ_WORKER_MCAST_GRID
#define NUM_WORKER_CORES_TO_MCAST CQ_NUM_WORKER_CORES

#else
#error "Unsupported CQ kernel variant for blackhole-py fixed config"
#endif
